# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Competentions', '0002_customcompetention'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCompetentionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalStandart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalStandartCompetention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalStandartCompetentionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customcompetention',
            name='neccessaryKnowledges',
        ),
        migrations.RemoveField(
            model_name='customcompetention',
            name='neccessarySkills',
        ),
        migrations.RemoveField(
            model_name='customcompetention',
            name='workActions',
        ),
        migrations.AlterField(
            model_name='customcompetention',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='educationalstandartcompetention',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Competentions.EducationalStandartCompetentionGroup'),
        ),
        migrations.AddField(
            model_name='educationalstandart',
            name='educationalStandartCompetentions',
            field=models.ManyToManyField(to='Competentions.EducationalStandartCompetention'),
        ),
        migrations.AddField(
            model_name='customcompetentionlist',
            name='customCopetentions',
            field=models.ManyToManyField(to='Competentions.CustomCompetention'),
        ),
        migrations.AddField(
            model_name='customcompetentionlist',
            name='generalProfessionalCompetentions',
            field=models.ManyToManyField(to='Competentions.EducationalStandartCompetention'),
        ),
        migrations.AddField(
            model_name='customcompetentionlist',
            name='neccessaryKnowledges',
            field=models.ManyToManyField(to='Competentions.NeccessaryKnowledge'),
        ),
        migrations.AddField(
            model_name='customcompetentionlist',
            name='neccessarySkills',
            field=models.ManyToManyField(to='Competentions.NeccessarySkill'),
        ),
        migrations.AddField(
            model_name='customcompetentionlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcompetentionlist',
            name='workActions',
            field=models.ManyToManyField(to='Competentions.WorkAction'),
        ),
    ]
