# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Competentions', '0005_auto_20171220_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='educationalstandart',
            name='education_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='educationalstandart',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customcompetentionlist',
            name='customCopetentions',
            field=models.ManyToManyField(blank=True, to='Competentions.CustomCompetention'),
        ),
        migrations.AlterField(
            model_name='customcompetentionlist',
            name='generalProfessionalCompetentions',
            field=models.ManyToManyField(blank=True, to='Competentions.EducationalStandartCompetention'),
        ),
        migrations.AlterField(
            model_name='customcompetentionlist',
            name='neccessaryKnowledges',
            field=models.ManyToManyField(blank=True, to='Competentions.NeccessaryKnowledge'),
        ),
        migrations.AlterField(
            model_name='customcompetentionlist',
            name='neccessarySkills',
            field=models.ManyToManyField(blank=True, to='Competentions.NeccessarySkill'),
        ),
        migrations.AlterField(
            model_name='customcompetentionlist',
            name='workActions',
            field=models.ManyToManyField(blank=True, to='Competentions.WorkAction'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='competentionLists',
            field=models.ManyToManyField(blank=True, to='Competentions.CustomCompetentionList'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
